<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
	<div class="container">
        <h1 class="color-green pull-left">Contacto</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="/">Inicio</a> <span class="divider">/</span></li>
            <li class="active">Contacto</li>
        </ul>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container">		
	<div class="row-fluid">
		<div class="span9">
<!--            <div id="map" class="map map-box map-box-space margin-bottom-40">
            </div>-/map-->

            <p>Si necesitas cotizar un servicio en particular completa los campos a continuación y envíanos un mensaje, te contactaremos a la brevedad.</p><br />
			<form id="formulario-contacto" />
                <label>Nombre</label>
                <input type="text" class="span7"  id="nombre"/>
                <label>Correo <span class="color-red">*</span></label>
                <input type="text" class="span7" id="correo" />
                <label>Mensaje</label>
                <textarea rows="8" class="span10" id="mensaje"></textarea>
                <p><button type="button" class="btn-u" onclick="enviarMensaje()">Enviar mensaje</button></p>
            </form>
        </div><!--/span9-->

        <div class="span3">
            <!-- Contacts -->
            <div class="headline"><h3>Contáctenos</h3></div>
            <ul class="unstyled who margin-bottom-20">
                <!--<li><a href="#"><i class="icon-home"></i>5B Streat, City 50987 New Town US</a></li>-->
                 <li><a href="#"><i class="icon-user"></i>José Muñoz Becerra </a></li>
                <li><a href="#"><i class="icon-envelope-alt"></i>jmunoz@jyj.cl</a></li>
                <li><a href="#"><i class="icon-phone-sign"></i>+56-9-84804060</a></li>
                <li><a href="#"><i class="icon-globe"></i>http://www.jyj.cl</a></li>
            </ul>
            <hr>
             <ul class="unstyled who margin-bottom-20">
                <!--<li><a href="#"><i class="icon-home"></i>5B Streat, City 50987 New Town US</a></li>-->
                    <li><a href="#"><i class="icon-user"></i>Jorge Enriquez Toledo</a></li>
                <li><a href="#"><i class="icon-envelope-alt"></i>enriques@jyj.cl</a></li>
                <li><a href="#"><i class="icon-phone-sign"></i>+56-9-72978139</a></li>
                <li><a href="#"><i class="icon-globe"></i>http://www.jyj.cl</a></li>
            </ul>


            <!-- Business Hours -->
            <div class="headline"><h3>Horario de trabajo</h3></div>
            <ul class="unstyled">
                <li><strong>Lunes a Viernes:</strong> 8am to 8pm</li>
                <li><strong>Sabado:</strong> 8am to 4pm</li>
                <li><strong>Domingo:</strong> Sin servicio</li>
            </ul>

            <!-- Why we are? -->
<!--            <div class="headline"><h3>Why we are?</h3></div>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.</p>
            <ul class="unstyled">
                <li><i class="icon-ok color-green"></i> Odio dignissimos ducimus</li>
                <li><i class="icon-ok color-green"></i> Blanditiis praesentium volup</li>
                <li><i class="icon-ok color-green"></i> Eos et accusamus</li>
            </ul>-->
        </div><!--/span3-->        
    </div><!--/row-fluid-->        

    <!-- Our Clients -->
<!--    <div id="clients-flexslider" class="flexslider home clients">
        <div class="headline"><h3>Our Clients</h3></div>    
        <ul class="slides">
            <li>
                <a href="#">
                    <img src="assets/img/clients/hp_grey.png" alt="" /> 
                    <img src="assets/img/clients/hp.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/igneus_grey.png" alt="" /> 
                    <img src="assets/img/clients/igneus.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/vadafone_grey.png" alt="" /> 
                    <img src="assets/img/clients/vadafone.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/walmart_grey.png" alt="" /> 
                    <img src="assets/img/clients/walmart.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/aztec_grey.png" alt="" /> 
                    <img src="assets/img/clients/aztec.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/cisco_grey.png" alt="" /> 
                    <img src="assets/img/clients/cisco.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/cocacola_grey.png" alt="" /> 
                    <img src="assets/img/clients/cocacola.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
        </ul>
    </div>/flexslider-->
    <!-- //End Our Clients -->
</div><!--/container-->		
<!--=== End Content Part ===-->
