
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
	<div class="container">
        <h1 class="color-green pull-left">Servicios</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="/">Inicio</a> <span class="divider">/</span></li>
            <li class="active">Servicios</li>
        </ul>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->


<div class="container">
	<div class="row-fluid">
            
            
<div class="headline"><h3>Algunos de nuestros servicios</h3></div>
<ul class="thumbnails">
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Ampliaciones" href="<?php echo $this->basePath('img/fotos/ampliaciones.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/ampliaciones.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Ampliaciones</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Cerámicos" href="<?php echo $this->basePath('img/fotos/instalacion_ceramicos.jpg')?>">

                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/ceramicos.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Instalación de piso flotante, Alfombras y ceramicos</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Estructuras de aluminio" href="<?php echo $this->basePath('img/fotos/cielo_falso.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/cieloFalso.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Trabajos estructuras de aluminio</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Trabajos en carpinteria" href="<?php echo $this->basePath('img/fotos/techo_luz.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/techodeLuz.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Trabajos en carpintería</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            
           
        </ul>
<ul class="thumbnails">
            
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Gasfiteria" href="<?php echo $this->basePath('img/fotos/gasfiteria.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/gasfiteria.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Gasfitería</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Electricidad" href="<?php echo $this->basePath('img/fotos/electrico.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/cieloYelectrico.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Electricidad</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Remodelaciones" href="<?php echo $this->basePath('img/fotos/remodelaciones.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/muebleria.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Remodelaciones</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
           <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Trabajos en Pintura" href="<?php echo $this->basePath('img/fotos/pintado.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/pintura1.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Trabajos en Pintura</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
        </ul>

        </div>
</div>