<!--=== Breadcrumbs ===-->
<div class="row-fluid breadcrumbs margin-bottom-40">
	<div class="container">
        <h1 class="pull-left">Equipo</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="/">Inicio</a> <span class="divider">/</span></li>
            <li class="active">Equipo</li>
        </ul>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container">		
	<div class="row-fluid margin-bottom-30">
    	<div class="span6">
            <p>Nuestra empresa esta formada por profesionales altamente capacitados en las áreas de construcción y servicios, debido a esto ofrecemos servicios de alta calidad y garantizados, además de contar con una alta satisfacción de nuestros clientes </p>
            <ul class="unstyled">
                <li><i class="icon-ok color-green"></i> Confianza</li>
                <li><i class="icon-ok color-green"></i> Calidad</li>
                <li><i class="icon-ok color-green"></i> Experiencia</li>
                <li><i class="icon-ok color-green"></i> Profesionalismo</li>
                <li><i class="icon-ok color-green"></i> Compromiso con nuestros clientes</li>
            </ul><br />

            <!-- Blockquotes -->
            <blockquote>
                <p>Empieza por hacer lo necesario, luego haz lo posible, y de pronto estarás logrando lo imposible .</p>
                <small>San Francisco de Asis.</small>
            </blockquote>
        </div>
    	<div class="span6">
             <img class="img-border" src="<?php echo $this->basePath('img/equipo2.jpg');?>" alt="Image 6" />
            <!--<iframe src="http://player.vimeo.com/video/9679622" width="100%" height="327" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>--> 
        </div>
    </div><!--/row-fluid-->

	<!-- Meer Our Team -->
	<div class="headline"><h3>Nuestro equipo</h3></div>
    <ul class="thumbnails team">
        <li class="span3">
            <div class="thumbnail-style">
                <!--<img src="assets/img/others/2.jpg" alt="" />-->
                <h3><a>José Luis Enrique Toledo</a> <small>Técnico profesional en construcción</small></h3>
                <p>Técnico Profesional en Construcción, con 5 años en el rubro...</p>
<!--                <ul class="unstyled inline">
                	<li><a href="#"><i class="icon-facebook"></i></a></li>
                	<li><a href="#"><i class="icon-twitter"></i></a></li>
                	<li><a href="#"><i class="icon-google-plus"></i></a></li>
                </ul>-->
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail-style">
                <!--<img src="assets/img/others/7.jpg" alt="" />-->
                <h3><a>Jorge Enriques Toledo</a> <small>Mecánico industrial</small></h3>
                <p>Mecánico Industrial, con 5 años en el rubro....</p>
<!--                <ul class="unstyled inline team">
                	<li><a href="#"><i class="icon-facebook"></i></a></li>
                	<li><a href="#"><i class="icon-twitter"></i></a></li>
                	<li><a href="#"><i class="icon-google-plus"></i></a></li>
                </ul>-->
            </div>
        </li>
<!--        <li class="span3">
            <div class="thumbnail-style">
                <img src="assets/img/others/3.jpg" alt="" />
                <h3><a>Porta Gravida</a> <small>VP of Operations</small></h3>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem...</p>
                <ul class="unstyled inline team">
                	<li><a href="#"><i class="icon-facebook"></i></a></li>
                	<li><a href="#"><i class="icon-twitter"></i></a></li>
                	<li><a href="#"><i class="icon-google-plus"></i></a></li>
                </ul>
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail-style">
                <img src="assets/img/others/6.jpg" alt="" />
                <h3><a>Donec Elit</a> <small>Director, R &amp; D Talent</small></h3>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem...</p>
                <ul class="unstyled inline team">
                	<li><a href="#"><i class="icon-facebook"></i></a></li>
                	<li><a href="#"><i class="icon-twitter"></i></a></li>
                	<li><a href="#"><i class="icon-google-plus"></i></a></li>
                </ul>
            </div>
        </li>-->
    </ul><!--/thumbnails-->
	<!-- //End Meer Our Team -->

    <!-- Our Clients -->
<!--    <div id="clients-flexslider" class="flexslider home clients">
        <div class="headline"><h3>Our Clients</h3></div>    
        <ul class="slides">
            <li>
                <a href="#">
                    <img src="assets/img/clients/hp_grey.png" alt="" /> 
                    <img src="assets/img/clients/hp.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/igneus_grey.png" alt="" /> 
                    <img src="assets/img/clients/igneus.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/vadafone_grey.png" alt="" /> 
                    <img src="assets/img/clients/vadafone.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/walmart_grey.png" alt="" /> 
                    <img src="assets/img/clients/walmart.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/aztec_grey.png" alt="" /> 
                    <img src="assets/img/clients/aztec.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/cisco_grey.png" alt="" /> 
                    <img src="assets/img/clients/cisco.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/cocacola_grey.png" alt="" /> 
                    <img src="assets/img/clients/cocacola.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
        </ul>
    </div>/flexslider-->
    <!-- //End Our Clients -->
</div><!--/container-->		
<!--=== End Content Part ===-->
