
<!--=== Breadcrumbs ===-->
<div class="breadcrumbs margin-bottom-40">
	<div class="container">
        <h1 class="color-green pull-left">Proyectos</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="/">Inicio</a> <span class="divider">/</span></li>
            <li class="active">Proyectos</li>
        </ul>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->


<!--=== Content Part ===-->
<div class="container">		
	<div class="row-fluid">
    	<div class="span12">
        	<div class="headline"><h3>Nuestras Soluciones a su Alcance</h3></div>
            <div class="clients-page margin-bottom-20">
            	<a class="img-hover" href="#">
                	<img src="<?php echo $this->basePath('img/fotos/playa.jpg')?>" alt="" />
                </a>                        
                <p>Si ha adjudicado una licitación Marítima en cualquier playa o lago y necesita implementar la infraestructura necesaria para hacer funcionar su negocio. Nosotros tenemos la experiencia que usted requiere, solo contactenos le aseguramos que con sus ideas y nuestra asesoria llegaremos a su proyecto soñado, enmarcandonos dentro de su presupuesto. <a class="linked color-green" href="#">http://www.concesionesmaritimas.cl/</a></p>
            </div>
            <div class="clients-page margin-bottom-20">
            	<a class="img-hover" href="#">
                	<img src="<?php echo $this->basePath('img/fotos/loza cemento o radier.jpg')?>" alt="" />
				</a>                        
                <p>Si esta pensando en comprar alguna propiedad usada y necesita reacondicionarla, hacer reparaciones o mantenimiento, no lo dude mas y consulte por nuestros servicios. Sus proyectos estarán en las mejores manos...contactenos. </p>
            </div>
            <div class="clients-page margin-bottom-20">
            	<a class="img-hover" href="#">
                	<img src="<?php echo $this->basePath('img/fotos/gasfiteria.jpg')?>" alt="" />
                	
				</a>                        
                <p>Si su hogar o Empresa presenta alguna emergencia de indole: Estructural, Eléctrico, Redes de alcantarillado, Gastifería...No lo dude y contactenos le daremos urgencia a su problema y una solución definitiva a su emergencia. </p>
            </div>
            <div class="clients-page margin-bottom-20">
            	<a class="img-hover" href="#">
                	<img src="<?php echo $this->basePath('img/fotos/ceramico.jpg')?>" alt="" />
				</a>                        
                <p>Si esta iniciando su emprendimiento y necesita implementar su negocio cotize con nosotros, lo visitaremos en terreno y le daremos un servicio personalizado acorde a lo que realmente necesita. No lo piense mas y haga de sus sueños una realidad. </p>
            </div>
            
        </div><!--/span9-->

<!--    	<div class="span3">
        	 Our Services 
            <div class="who margin-bottom-30">
                <div class="headline"><h3>Our Services</h3></div>
                <p>At vero eos et accusamus et iusto odio dign issimos ducimus qui blanditiis iusto.</p>
                <ul class="unstyled">
                    <li><a href="#"><i class="icon-desktop"></i>Vivamus imperdiet condimentum</a></li>
                    <li><a href="#"><i class="icon-bullhorn"></i>Anim pariatur cliche squid</a></li>
                    <li><a href="#"><i class="icon-globe"></i>Eget placerat felis consectetur</a></li>
                    <li><a href="#"><i class="icon-group"></i>Condimentum diam eget placerat</a></li>
                </ul>
            </div>

        	 About Us 
        	<div class="headline"><h3>About Us</h3></div>
            <p class="margin-bottom-30">At vero eos et acc usamus et iusto odio dign issimos ducimus atque corrupti quos dolores etrerum facilis est etenim a feugiat cupiditate non quos. <a class="read-more" href="#">Read more</a></p>

        	 Contact Us 
            <div class="who margin-bottom-30">
                <div class="headline"><h3>Contact Us</h3></div>
                <p>Vero facilis est etenim a feugiat cupiditate non quos etrerum facilis.</p>
                <ul class="unstyled">
                    <li><a href="#"><i class="icon-home"></i>5B amus ED554, New York, US</a></li>
                    <li><a href="#"><i class="icon-envelope-alt"></i>infp@example.com</a></li>
                    <li><a href="#"><i class="icon-phone-sign"></i>1(222) 5x86 x97x</a></li>
                    <li><a href="#"><i class="icon-globe"></i>http://www.example.com</a></li>
                </ul>
            </div>
        </div>/span3-->
    </div><!--/row-fluid-->        
</div><!--/container-->		
<!--=== End Content Part ===-->