


<?php echo $this->doctype(); ?>

<html lang="es">
<head>
    <!--<title>Unify | Welcome...</title>-->

    <!-- Meta -->
    <meta charset="utf-8">
    <?php echo $this->headTitle('J&J '. $this->translate('Construcciones'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    
    <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'unify/favicon.ico'))
               
                ->prependStylesheet($this->basePath('unify/assets/css/effects.css'))
                ->prependStylesheet($this->basePath('unify/assets/plugins/fancybox/source/jquery.fancybox.css'))
                ->prependStylesheet($this->basePath('unify/assets/css/headers/header1.css'))
                ->prependStylesheet($this->basePath('unify/assets/css/themes/default.css'))
//                ->prependStylesheet($this->basePath('unify/assets/plugins/parallax-slider/css/parallax-slider.css'))
                ->prependStylesheet($this->basePath('unify/assets/plugins/flexslider/flexslider.css'))
                ->prependStylesheet($this->basePath('unify/assets/plugins/revolution_slider/css/rs-style.css'))
                ->prependStylesheet($this->basePath('unify/assets/plugins/revolution_slider/rs-plugin/css/settings.css'))
//                <link rel="stylesheet" href="assets/plugins/revolution_slider/css/rs-style.css" media="screen" />
//    <link rel="stylesheet" href="assets/plugins/revolution_slider/rs-plugin/css/settings.css" media="screen" />    
                ->prependStylesheet($this->basePath('unify/assets/plugins/font-awesome/css/font-awesome.css'))
                
                ->prependStylesheet($this->basePath('unify/assets/css/style_responsive.css'))
                ->prependStylesheet($this->basePath('unify/assets/plugins/bootstrap/css/bootstrap-responsive.min.css'))
                ->prependStylesheet($this->basePath('unify/assets/css/headers/header1.css'))
                ->prependStylesheet($this->basePath('unify/assets/css/style.css'))
                ->prependStylesheet($this->basePath('unify/assets/plugins/bootstrap/css/bootstrap.min.css'))
                        
                        
                ?>
    <!-- Scripts -->
        <?php echo $this->headScript()
                
               ->prependFile($this->basePath('unify/assets/plugins/fancybox/source/jquery.fancybox.pack.js'))     
               ->prependFile($this->basePath('unify/assets/js/respond.js'))    
               ->prependFile($this->basePath('unify/assets/js/pages/index.js'))       
               ->prependFile($this->basePath('unify/assets/js/app.js'))       
               ->prependFile($this->basePath('unify/assets/plugins/back-to-top.js'))      
                ->prependFile($this->basePath('unify/assets/plugins/revolution_slider/rs-plugin/js/jquery.themepunch.plugins.min.js'))     
                ->prependFile($this->basePath('unify/assets/plugins/revolution_slider/rs-plugin/js/jquery.themepunch.revolution.min.js'))     
//               ->prependFile($this->basePath('unify/assets/plugins/parallax-slider/js/jquery.cslider.js'))     
//             ->prependFile($this->basePath('unify/assets/plugins/parallax-slider/js/modernizr.js'))      
            ->prependFile($this->basePath('unify/assets/plugins/flexslider/jquery.flexslider-min.js'))       
            ->prependFile($this->basePath('unify/assets/plugins/bootstrap/js/bootstrap.min.js'))    
            ->prependFile($this->basePath('unify/assets/js/modernizr.custom.js'))    
            ->prependFile($this->basePath('unify/assets/js/jquery-1.8.2.min.js'))
//            ->prependFile($this->basePath('js/jquery.min.js'))
//            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
//                <script type="text/javascript" src="assets/plugins/revolution_slider/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
//<script type="text/javascript" src="assets/plugins/revolution_slider/rs-plugin/js/jquery.themepunch.revolution.min.js"></script> 
        ; ?>
    
     <?php echo $this->inlineScript() ?>
    
    <!-- JS Global Compulsory -->			
    <!--
    <script type="text/javascript" src="assets/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="assets/js/modernizr.custom.js"></script>		
    <script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>	
     JS Implementing Plugins            
    <script type="text/javascript" src="assets/plugins/flexslider/jquery.flexslider-min.js"></script>
    <script type="text/javascript" src="assets/plugins/parallax-slider/js/modernizr.js"></script>
    <script type="text/javascript" src="assets/plugins/parallax-slider/js/jquery.cslider.js"></script> 
    <script type="text/javascript" src="assets/plugins/back-to-top.js"></script>
     JS Page Level            
    <script type="text/javascript" src="assets/js/app.js"></script>
    <script type="text/javascript" src="assets/js/pages/index.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            App.init();
            App.initSliders();
            Index.initParallaxSlider();
        });
    </script>
    [if lt IE 9]>
        <script src="assets/js/respond.js"></script>
    <![endif]
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-29166220-1']);
      _gaq.push(['_setDomainName', 'htmlstream.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
</script>-->
    <!-- CSS Global Compulsory-->
<!--    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="assets/css/style.css" />
    <link rel="stylesheet" href="assets/css/headers/header1.css" />
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="assets/css/style_responsive.css" />
    <link rel="shortcut icon" href="favicon.ico" />        
     CSS Implementing Plugins     
    <link rel="stylesheet" href="assets/plugins/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="assets/plugins/flexslider/flexslider.css" type="text/css" media="screen" />    	
    <link rel="stylesheet" href="assets/plugins/parallax-slider/css/parallax-slider.css" type="text/css" />
     CSS Theme     
    <link rel="stylesheet" href="assets/css/themes/default.css" id="style_color" />
    <link rel="stylesheet" href="assets/css/themes/headers/default.css" id="style_color-header-1" />    -->

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>	

<body>
<!--=== Style Switcher ===-->    
<!--<i class="style-switcher-btn icon-cogs"></i>-->
<!--<div class="style-switcher">
    <div class="theme-close"><i class="icon-remove"></i></div>
    <div class="theme-heading">Theme Colors</div>
    <ul class="unstyled">
        <li class="theme-default theme-active" data-style="default" data-header="light"></li>
        <li class="theme-blue" data-style="blue" data-header="light"></li>
        <li class="theme-orange" data-style="orange" data-header="light"></li>
        <li class="theme-red" data-style="red" data-header="light"></li>
        <li class="theme-light" data-style="light" data-header="light"></li>
    </ul>
</div>/style-switcher-->
<!--=== End Style Switcher ===-->    

<!--=== Top ===-->    
<div class="top">
    <div class="container">         
        <ul class="loginbar pull-right">
            <li><i class="icon-globe"></i><a>Lenguaje <i class="icon-sort-up"></i></a>
                <ul class="nav-list">
                    <li class="active"><a href="#">Español</a> <i class="icon-ok"></i></li>
<!--                    <li><a href="#">English</a></li>
                    <li><a href="#">Russian</a></li>
                    <li><a href="#">German</a></li>-->
                </ul>
            </li>   
            <li class="devider">&nbsp;</li>
            <li><a href="/servicios" class="login-btn">Ayuda</a></li>  
            <li class="devider">&nbsp;</li>
            <li><a href="http://mail.jyj.cl/etc/apps/webmail/" class="login-btn">Ingresa</a></li>   
        </ul>
    </div>      
</div><!--/top-->
<!--=== End Top ===-->    

<!--=== Header ===-->
<div class="header">               
    <div class="container"> 
        <!-- Logo -->       
        <div class="logo" style="margin: -30px">                                             
            <a href="/"><img id="logo-header" src="<?php echo $this->basePath('img/logo_verde.fw.png');?>" alt="Logo"  style="width: 90px;height: 90px"/></a>
        </div><!-- /logo -->        
                                    
        <!-- Menu -->       
        <div class="navbar">                                
            <div class="navbar-inner">                                  
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a><!-- /nav-collapse -->                                  
                <div class="nav-collapse collapse">                                     
                    <ul class="nav top-2">
                      
                        <li class="active">
                            <a href="<?php echo $this->basePath('');?>" class="dropdown-toggle" >Inicio
                                <!--<b class="caret"></b>-->                            
                            </a>
<!--                            <ul class="dropdown-menu">
                                <li class="active"><a href="index.html">Option1: Landing Page</a></li>
                                <li><a href="page_home.html">Option2: Header Option</a></li>
                                <li><a href="page_home4.html">Option3: Revolution Slider</a></li>
                                <li><a href="page_home5.html">Option4: Amazing Content</a></li>
                                <li><a href="page_home1.html">Option5: Mixed Content</a></li>
                                <li><a href="page_home2.html">Option6: Content with Sidebar</a></li>
                                <li><a href="page_home3.html">Option7: Aplle Style Slider</a></li>
                                <li><a href="page_home_all.html">Home All In One</a></li>
                            </ul>-->
                            <!--<b class="caret-out"></b>-->                        
                        </li>
                        <li>
                            <a href="/servicios" class="dropdown-toggle" >Servicios </a>
                        </li>
                        <li>
                            <a href="/equipo" class="dropdown-toggle">Equipo</a>
                        </li>
                        <li>
                            <a href="/proyectos" class="dropdown-toggle">Proyectos</a>
                        </li>
                        <li>
                            <a href="/contacto" class="dropdown-toggle" >Contacto </a>
                        </li>
<!--                       <li><a class="search"><i class="icon-search search-btn"></i></a></li>                               -->
                    </ul>
<!--                    <div class="search-open">
                        <div class="input-append">
                            <form />
                                <input type="text" class="span3" placeholder="Buscar" />
                                <button type="submit" class="btn-u">Buscar</button>
                            </form>
                        </div>
                    </div>-->
                </div><!-- /nav-collapse -->                                
            </div><!-- /navbar-inner -->
        </div><!-- /navbar -->                          
    </div><!-- /container -->               
</div><!--/header -->      
<!--=== End Header ===-->
     <?php echo $this->content; ?>
<!--=== Footer ===-->
<div class="footer">
	<div class="container">
		<div class="row-fluid">
			<div class="span4">
                <!-- About -->
		        <div class="headline"><h3>Quienes somos</h3></div>	
				
<p class="margin-bottom-25">Nuestra empresa esta formada por profesionales altamente capacitados en las áreas de construcción y servicios, debido a esto ofrecemos servicios de alta calidad y garantizados, además de contar con una alta satisfacción de nuestros clientes </p>
	            <!-- Monthly Newsletter -->
<!--		        <div class="headline"><h3>Monthly Newsletter</h3></div>	
				<p>Subscribe to our newsletter and stay up to date with the latest news and deals!</p>
				<form class="form-inline" />
					<div class="input-append">
						<input type="text" placeholder="Email Address" class="input-medium" />
						<button class="btn-u">Subscribe</button>
					</div>
				</form>							-->
			</div><!--/span4-->	
			
			<div class="span4">
                                 <div class="headline"><h3>Contáctanos</h3></div>
                      <address>
					 <ul class="unstyled who margin-bottom-20" style="color:#ffffff">
                <!--<li><a href="#"><i class="icon-home"></i>5B Streat, City 50987 New Town US</a></li>-->
                    <li style="color:#ffffff"><i class="icon-user"></i>Jorge Enriquez Toledo</li>
                <li style="color:#ffffff"><i class="icon-envelope-alt"></i>enriques@jyj.cl</li>
                <li style="color:#ffffff"><i class="icon-phone-sign"></i>+56-9-72978139</li>
                <li style="color:#ffffff"><i class="icon-globe"></i>http://www.jyj.cl></li>
            </ul>

                </address>
                        
			</div><!--/span4-->

			<div class="span4">
	            <!-- Monthly Newsletter -->
		        <div class="headline"><h3>Contáctanos</h3></div>	
<!--                <address>
					 <ul class="unstyled who margin-bottom-20" style="color:#ffffff">
                <li><a href="#"><i class="icon-home"></i>5B Streat, City 50987 New Town US</a></li>
                    <li style="color:#ffffff"><i class="icon-user"></i>Jorge Enriquez Toledo</li>
                <li style="color:#ffffff"><i class="icon-envelope-alt"></i>enriques@jyj.cl</li>
                <li style="color:#ffffff"><i class="icon-phone-sign"></i>+56-9-72978139</li>
                <li style="color:#ffffff"><i class="icon-globe"></i>http://www.jyj.cl></li>
            </ul>

                </address>-->
                        
                         <address  class="headline">
							 <ul class="unstyled who margin-bottom-20">
                <!--<li><a href="#"><i class="icon-home"></i>5B Streat, City 50987 New Town US</a></li>-->
                    <li style="color:#ffffff"><i class="icon-user"></i>José Muñoz Becerra</li>
                <li style="color:#ffffff"><i class="icon-envelope-alt"></i>jmunoz@jyj.cl</li>
                <li style="color:#ffffff"><i class="icon-phone-sign"></i>+56-9-84804060</li>
                <li style="color:#ffffff"><i class="icon-globe"></i>http://www.jyj.cl></li>
            </ul>


                </address>

                <!-- Stay Connected -->
<!--		        <div class="headline"><h3>Nuestra red</h3></div>	
                <ul class="social-icons">
                    <li><a href="#" data-original-title="Feed" class="social_rss"></a></li>
                    <li><a href="#" data-original-title="Facebook" class="social_facebook"></a></li>
                    <li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li>
                    <li><a href="#" data-original-title="Goole Plus" class="social_googleplus"></a></li>
                    <li><a href="#" data-original-title="Pinterest" class="social_pintrest"></a></li>
                    <li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>
                    <li><a href="#" data-original-title="Vimeo" class="social_vimeo"></a></li>
                </ul>
			</div>/span4-->
		</div><!--/row-fluid-->	
	</div><!--/container-->	
</div><!--/footer-->	
<!--=== End Footer ===-->

<!--=== Copyright ===-->
<div class="copyright">
	<div class="container">
		<div class="row-fluid">
			<div class="span8">						
	            <p>2015 &copy; J&J. Todos los derechos reservados
			</div>
			<div class="span4">	
				<!--<a href="index.html"><img id="logo-footer" src="<?php echo $this->basePath('img/logo_verde.fw.png')?>" class="pull-right" alt="" style="width:50px" /></a>-->
			</div>
		</div><!--/row-fluid-->
	</div><!--/container-->	
</div><!--/copyright-->	
<!--=== End Copyright ===-->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initFancybox();        
    });
</script>
<script type="text/javascript">
    jQuery(document).ready(function() {
      	App.init();
        App.initSliders();
        Index.initRevolutionSlider();        
    });
</script>
<!--[if lt IE 9]>
    <script src="assets/js/respond.js"></script>
<![endif]-->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29166220-1']);
  _gaq.push(['_setDomainName', 'htmlstream.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</body>
</html>	