<!--=== Slider ===-->
<div class="fullwidthbanner-container">
    <div class="fullwidthabnner">
        <ul>
            <!-- THE FIRST SLIDE -->
            <li data-transition="3dcurtain-vertical" data-slotamount="10" data-masterspeed="300" data-thumb="<?php echo $this->basePath('unify/assets/img/sliders/revolution/thumbs/thumb1.jpg');?>">

                <!-- THE MAIN IMAGE IN THE FIRST SLIDE -->
                <img src="<?php echo $this->basePath('img/banner2.jpg')?>" />

                

                <div class="caption randomrotate" data-x="189" data-y="76" data-speed="600" data-start="1100" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/albañileria.jpg"');?>"/>
                </div>

                <div class="caption randomrotate" data-x="0" data-y="92" data-speed="600" data-start="1200" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/ampliaciones.jpg');?>" alt="Image 3" />
                </div>

                <div class="caption randomrotate" data-x="200" data-y="209" data-speed="600" data-start="1300" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/ceramica1.jpg')?>" alt="Image 4" />
                </div>

                <div class="caption randomrotate" data-x="97" data-y="117" data-speed="300" data-start="1400" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/cielo_electrico.jpg')?>" alt="Image 5" />
                </div>

                <div class="caption randomrotate" data-x="14" data-y="222" data-speed="600" data-start="1500" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/gasfiteria.jpg')?>" alt="Image 6" />
                </div>

                <div class="caption randomrotate" data-x="638" data-y="201" data-speed="300" data-start="1600" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/loza_cemento.jpg')?>" alt="Image 7" />
                </div>

                <div class="caption randomrotate" data-x="717" data-y="294" data-speed="300" data-start="1700" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/obras_menores.jpg')?>" alt="Image 8" />
                </div>

                <div class="caption randomrotate" data-x="682" data-y="79" data-speed="300" data-start="1800" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/pintura1.jpg')?>" alt="Image 9" />
                </div>

                <div class="caption randomrotate" data-x="807" data-y="71" data-speed="300" data-start="1900" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/piso_flotante.jpg')?>" alt="Image 10" />
                </div>

                <div class="caption randomrotate" data-x="818" data-y="271" data-speed="300" data-start="2000" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/techo_luz.jpg')?>" alt="Image 11" />
                </div>

                <div class="caption randomrotate" data-x="95" data-y="248" data-speed="300" data-start="2100" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/quincho.jpg')?>" alt="Image 12" />
                </div>

                <div class="caption randomrotate" data-x="762" data-y="165" data-speed="300" data-start="2200" data-easing="easeOutExpo">
                     <img class="img-border" src="<?php echo $this->basePath('img/mini100x100/techo_luz2.jpg')?>" alt="Image 13" />
                </div>
                <div class="caption large_text sfb bg-black-opacity" data-x="176" data-y="220" data-speed="1800" data-start="2200" data-easing="easeOutExpo" >
                    ¿Tienes alguna idea para tu hogar?<br>
                     <span style="color: #ffcc00;">Nosotros la hacemos realidad</span> 
                     
                </div>
            </li>

            <!-- THE SECOND SLIDE -->
            <li data-transition="papercut" data-slotamount="15" data-masterspeed="300" data-delay="9400" data-thumb="assets/img/sliders/revolution/thumbs/thumb2.jpg">

                <!-- THE MAIN IMAGE IN THE SECOND SLIDE -->                                               
                 <img src="<?php echo $this->basePath('img/banner4.jpg')?>" />

                <div class="caption very_big_white lfl stl" data-x="18" data-y="343" data-speed="300" data-start="500" data-easing="easeOutExpo" data-end="8800" data-endspeed="300" data-endeasing="easeInSine">
                     No sueñes con tu hogar ideal
                </div>

                <div class="caption big_white lfl stl" data-x="18" data-y="390" data-speed="700" data-start="1600" data-easing="easeOutExpo" data-end="9100" data-endspeed="300" data-endeasing="easeInSine">
                     Trabajando con nosotros lo crearemos.
                </div>
                  <div class="caption lft ltb" data-x="750" data-y="100" data-speed="600" data-start="1100" data-easing="easeOutExpo" data-end="3100" data-endspeed="600" data-endeasing="easeInSine">
                     <img class="img-border" src="<?php echo $this->basePath('img/miniaturas/ceramico_TrabElectico.jpg"');?>"  alt="Image 2"/>
                </div>
                 <div class="caption large_text sfr" data-x="790" data-y="440" data-speed="300"  data-start="1100" data-easing="easeOutExpo"data-end="3100" data-endspeed="300" data-endeasing="easeInSine">
                    <span style="color: #72c02c;">   Ceramicos </span>
                </div>


<!--                <div class="caption big_black sfb stb" data-x="780" data-y="320" data-speed="300" data-start="1700" data-easing="easeOutExpo" data-end="3200" data-endspeed="300" data-endeasing="easeInSine">
                     $ 128
                </div>-->

                <div class="caption lft ltb" data-x="750" data-y="100" data-speed="600" data-start="3600" data-easing="easeOutExpo" data-end="5600" data-endspeed="600" data-endeasing="easeInSine">
                     <img class="img-border" src="<?php echo $this->basePath('img/miniaturas/quincho.jpg"');?>" alt="Image 6" />
                </div>

                <div class="caption large_text sfr" data-x="790" data-y="440"  data-speed="300" data-start="3900" data-easing="easeOutExpo" data-end="5800" data-endspeed="300" data-endeasing="easeInSine">
                    <span style="color: #72c02c;"> Quinchos</span>
                </div>

<!--                <div class="caption big_black sfb stb" data-x="780" data-y="320" data-speed="300" data-start="4200" data-easing="easeOutExpo" data-end="5700" data-endspeed="300" data-endeasing="easeInSine">
                     $ 116
                </div>-->

                <div class="caption lft ltb" data-x="750" data-y="100" data-speed="600" data-start="6100" data-easing="easeOutExpo" data-end="8100" data-endspeed="300" data-endeasing="easeInSine">
                     <img  class="img-border" src="<?php echo $this->basePath('img/miniaturas/muebleria.jpg"');?>" alt="Image 9" />
                </div>

                <div class="caption large_text sfr" data-x="600" data-y="440"  data-speed="300" data-start="6400" data-easing="easeOutExpo" data-end="8300" data-endspeed="300" data-endeasing="easeInSine">
                    <span style="color: #72c02c;"> Mueblería  y mucho más...</span>
                </div>

<!--                <div class="caption big_black sfb stb" data-x="780" data-y="320" data-speed="300" data-start="6700" data-easing="easeOutExpo" data-end="8200" data-endspeed="300" data-endeasing="easeInSine">
                     $ 142
                </div>-->
            </li>

            <!-- THE THIRD SLIDE -->
            <li data-transition="slideleft" data-slotamount="1" data-masterspeed="300" data-thumb="assets/img/sliders/revolution/thumbs/thumb3.jpg">

                <!-- THE MAIN IMAGE IN THE THIRD SLIDE -->                                               
                <img src="<?php echo $this->basePath('img/banner6.jpg')?>" />

                <div class="caption large_text sft" data-x="10" data-y="44" data-speed="300" data-start="800" data-easing="easeOutExpo">
                     Profesionales altamente capacitados
                </div>

                <div class="caption medium_text sfl" data-x="39" data-y="82" data-speed="300" data-start="1100" data-easing="easeOutExpo">
                     &
                </div>

                <div class="caption large_text sfr" data-x="88" data-y="78" data-speed="300" data-start="1100" data-easing="easeOutExpo">
                     <span style="color: #72c02c;">Con la experiencia que da confianza</span>
                </div>

<!--                <div class="caption lfl" data-x="10" data-y="150" data-speed="800" data-start="900" data-easing="easeOutExpo">
                    <img  src="<?php //echo $this->basePath('img/calidad.png"');?>" alt="Image 9" />
                </div>

                <div class="caption lfl" data-x="210" data-y="245" data-speed="600" data-start="1000" data-easing="easeOutExpo">
                    <img  src="<?php //echo $this->basePath('img/garantia.png"');?>" alt="Image 9" />
                </div>-->

                <div class="caption lfl" data-x="400" data-y="245" data-speed="300" data-start="500"  data-easing="easeOutExpo">
                       <img  src="<?php echo $this->basePath('img/calidad.png"');?>" alt="Image 9" />
                </div>

<!--                <div class="caption lft" data-x="500" data-y="130" data-speed="300" data-start="500" data-easing="easeOutExpo">
                    <img  class="img-border" src="<?php //echo $this->basePath('img/miniaturas/muebleria.jpg"');?>" alt="Image 9" />
                </div>-->
            </li>

<!--             THE FOURTH SLIDE 
            <li data-transition="flyin" data-slotamount="1" data-masterspeed="300" data-thumb="assets/img/sliders/revolution/thumbs/thumb4.jpg">
                
                 THE MAIN IMAGE IN THE FOURTH SLIDE                                 
                <img src="<?php //echo $this->basePath('img/banner6.jpg')?>" />

                <div class="caption lfb boxshadow" data-x="0" data-y="120" data-speed="900" data-start="500" data-easing="easeOutBack">
                     <iframe src="http://player.vimeo.com/video/54035990?title=0&amp;byline=0&amp;portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe> 
                </div>

                <div class="caption sft big_black" data-x="550" data-y="120" data-speed="300" data-start="1200" data-easing="easeOutExpo">
                     Video Support
                </div>
                
                <div class="caption sft big_white" data-x="550" data-y="162" data-speed="300" data-start="1300" data-easing="easeOutExpo">
                     Vimeo Example
                </div>
                
                <div class="caption lfb medium_grey" data-x="550" data-y="215" data-speed="300" data-start="1400" data-easing="easeOutExpo">
                     You can easily add
                </div>
                
                <div class="caption lfb medium_grey" data-x="550" data-y="240" data-speed="300" data-start="1500" data-easing="easeOutExpo">   
                     Vimeo & Youtube Videos
                </div>
                
                <div class="caption lfb medium_grey" data-x="550" data-y="265" data-speed="300" data-start="1600" data-easing="easeOutExpo">
                     to your Slides
                </div>
            </li>-->
        </ul>

        <div class="tp-bannertimer tp-bottom"></div>
    </div>
</div>
<!--=== End Slider ===-->

<!--=== Purchase Block ===-->
<div class="row-fluid purchase margin-bottom-30">
    <div class="container">
		<div class="span9">
            <span>Una empresa de confianza.</span>
            <p>Con una gran variedad de servicios y profesionales con experiencia</p>
        </div>
        <a href="/contacto" class="btn-buy hover-effect">¡Cotiza ahora!</a>
    </div>
</div><!--/row-fluid-->
<!-- End Purchase Block -->

<!--=== Content Part ===-->
<div class="container">	
	<!-- Service Blocks -->
<!--	<div class="row-fluid">
    	<div class="span4">
    		<div class="service clearfix">
                <i class="icon-resize-small"></i>
    			<div class="desc">
    				<h4>Fully Responsive</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
    			</div>
    		</div>	
    	</div>
    	<div class="span4">
    		<div class="service clearfix">
                <i class="icon-cogs"></i>
    			<div class="desc">
    				<h4>HTML5 + CSS3</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
    			</div>
    		</div>	
    	</div>
    	<div class="span4">
    		<div class="service clearfix">
                <i class="icon-plane"></i>
    			<div class="desc">
    				<h4>Launch Ready</h4>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
    			</div>
    		</div>	
    	</div>			    
	</div>/row-fluid-->
	<!-- //End Service Blokcs -->

	<!-- Recent Works -->
	<div class="headline"><h3>Algunos de nuestros servicios</h3></div>
    <ul class="thumbnails">
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Ampliaciones" href="<?php echo $this->basePath('img/fotos/ampliaciones.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/ampliaciones.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Ampliaciones</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Cerámicos" href="<?php echo $this->basePath('img/fotos/instalacion_ceramicos.jpg')?>">

                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/ceramicos.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Instalación de piso flotante, Alfombras y ceramicos</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Estructuras de aluminio" href="<?php echo $this->basePath('img/fotos/cielo_falso.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/cieloFalso.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Trabajos estructuras de aluminio</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            <li class="span3">
                <div class="thumbnail-style">
                    <a class="fancybox-button zoomer" data-rel="fancybox-button" title="Trabajos en carpinteria" href="<?php echo $this->basePath('img/fotos/techo_luz.jpg')?>">
                        <div class="overlay-zoom">	
                            <img src="<?php echo $this->basePath('img/miniaturas/techodeLuz.jpg')?>" alt="">
                            <div class="zoom-icon"></div>					
                        </div>												
                    </a>
                    <h3><a href="#">Trabajos en carpintería</a></h3>
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem. <a class="read-more" href="#">Read more</a></p>-->
                </div>
            </li>
            
           
        </ul>
	<!-- //End Recent Works -->
    
<!--	 Information Blokcs 
	<div class="row-fluid margin-bottom-20">
    	 Who We Are 
		<div class="span8">
			<div class="headline"><h3>Algunos de nuestros servicios</h3></div>
			<p><img class="pull-left lft-img-margin img-width-200" src="assets/img/carousel/6.jpg" alt="" />Unify is an incredibly beautiful responsive Bootstrap Template for corporate and creative professionals. It works on all major web browsers, tablets and phone.</p>	
            <ul class="unstyled">
            	<li><i class="icon-ok color-green"></i> Donec id elit non mi porta gravida</li>
            	<li><i class="icon-ok color-green"></i> Corporate and Creative</li>
            	<li><i class="icon-ok color-green"></i> Responsive Bootstrap Template</li>
            	<li><i class="icon-ok color-green"></i> Corporate and Creative</li>
            </ul><br />

            <blockquote class="hero-unify">
                <p>Award winning digital agency. We bring a personal and effective approach to every project we work on, which is why. Unify is an incredibly beautiful responsive Bootstrap Template for corporate professionals.</p>
                <small>CEO, Jack Bour</small>
            </blockquote>
        </div>/span8        -->

        <!-- Latest Shots -->
<!--        <div class="span4">
			<div class="headline"><h3>Latest Shots</h3></div>
			<div id="myCarousel" class="carousel slide">
                <div class="carousel-inner">
                  <div class="item active">
                    <img src="assets/img/carousel/5.jpg" alt="" />
                    <div class="carousel-caption">
                      <p>Cras justo odio, dapibus ac facilisis in, egestas.</p>
                    </div>
                  </div>
                  <div class="item">
                    <img src="assets/img/carousel/4.jpg" alt="" />
                    <div class="carousel-caption">
                      <p>Cras justo odio, dapibus ac facilisis in, egestas.</p>
                    </div>
                  </div>
                  <div class="item">
                    <img src="assets/img/carousel/3.jpg" alt="" />
                    <div class="carousel-caption">
                      <p>Cras justo odio, dapibus ac facilisis in, egestas.</p>
                    </div>
                  </div>
                </div>
                
                <div class="carousel-arrow">
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="icon-angle-left"></i></a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="icon-angle-right"></i></a>
                </div>
			</div>
        </div>/span4
	</div>/row-fluid	
	 //End Information Blokcs 

	 Our Clients 
	<div id="clients-flexslider" class="flexslider home clients">
        <div class="headline"><h3>Nuestros proyectos</h3></div>	
		<ul class="slides">
			<li>
                <a href="#">
                    <img src="<?php echo $this->basePath('unify/assets/img/clients/hp_grey.png');?>" alt="" /> 
                    <img src="<?php echo $this->basePath('unify/assets/img/clients/hp.png');?>" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/igneus_grey.png" alt="" /> 
                    <img src="assets/img/clients/igneus.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/vadafone_grey.png" alt="" /> 
                    <img src="assets/img/clients/vadafone.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/walmart_grey.png" alt="" /> 
                    <img src="assets/img/clients/walmart.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/aztec_grey.png" alt="" /> 
                    <img src="assets/img/clients/aztec.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/cisco_grey.png" alt="" /> 
                    <img src="assets/img/clients/cisco.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/cocacola_grey.png" alt="" /> 
                    <img src="assets/img/clients/cocacola.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/shell_grey.png" alt="" /> 
                    <img src="assets/img/clients/shell.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/natural_grey.png" alt="" /> 
                    <img src="assets/img/clients/natural.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/gamescast_grey.png" alt="" /> 
                    <img src="assets/img/clients/gamescast.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/everyday_grey.png" alt="" /> 
                    <img src="assets/img/clients/everyday.png" class="color-img" alt="" />
                </a>
            </li>
			<li>
                <a href="#">
                    <img src="assets/img/clients/spinworkx_grey.png" alt="" /> 
                    <img src="assets/img/clients/spinworkx.png" class="color-img" alt="" />
                </a>
            </li>
		</ul>
	</div>/flexslider
	 //End Our Clients 
</div>/container		-->
<!-- End Content Part -->